title: jagilber
description: jagilber info
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
  - about.md
  - projects.md
theme: jekyll-theme-midnight
show_downloads: true
google_analytics:
