title: jason gilbertson
# description: jagilber info
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
#theme: jekyll-theme-midnight
show_downloads: false
google_analytics:
